$rosewater = rgb(ddf7ff)
$rosewaterAlpha = ddf7ff

$flamingo = rgb(cddbf4)
$flamingoAlpha = cddbf4

$pink = rgb(86a7df)
$pinkAlpha = 86a7df

$mauve = rgb(82fb9c)
$mauveAlpha = 82fb9c

$red = rgb(50f872)
$redAlpha = 50f872

$maroon = rgb(50f7a3)
$maroonAlpha = 50f7a3

$peach = rgb(50f7d4)
$peachAlpha = 50f7d4

$yellow = rgb(50f7d4)
$yellowAlpha = 50f7d4

$green = rgb(4fe88f)
$greenAlpha = 4fe88f

$teal = rgb(7cf8f7)
$tealAlpha = 7cf8f7

$sky = rgb(d1fffe)
$skyAlpha = d1fffe

$sapphire = rgb(c4d2ed)
$sapphireAlpha = c4d2ed

$blue = rgb(829dd4)
$blueAlpha = 829dd4

$lavender = rgb(cddbf4)
$lavenderAlpha = cddbf4

$text = rgb(ddf7ff)
$textAlpha = ddf7ff

$subtext1 = rgb(b5c5db)
$subtext1Alpha = b5c5db

$subtext0 = rgb(6a6e95)
$subtext0Alpha = 6a6e95

$overlay2 = rgb(b5c5db)
$overlay2Alpha = b5c5db

$overlay1 = rgb(86a7df)
$overlay1Alpha = 86a7df

$overlay0 = rgb(6a6e95)
$overlay0Alpha = 6a6e95

$surface2 = rgb(2d3450)
$surface2Alpha = 2d3450

$surface1 = rgb(1f253a)
$surface1Alpha = 1f253a

$surface0 = rgb(151828)
$surface0Alpha = 151828

$base = rgb(0b0c16)
$baseAlpha = 0b0c16

$mantle = rgb(080910)
$mantleAlpha = 080910

$crust = rgb(06060c)
$crustAlpha = 06060c
