# The basic colors
foreground              #ddf7ff
background              #0b0c16
selection_foreground    #0b0c16
selection_background    #ddf7ff

# Cursor colors
cursor                  #ddf7ff
cursor_text_color       #0b0c16

# URL underline color when hovering with mouse
url_color               #ddf7ff

# Kitty window border colors
active_border_color     #cddbf4
inactive_border_color   #6a6e95
bell_border_color       #50f7d4

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #06060c
active_tab_background   #82fb9c
inactive_tab_foreground #ddf7ff
inactive_tab_background #080910
tab_bar_background      #06060c

# Colors for marks (marked text in the terminal)
mark1_foreground #0b0c16
mark1_background #cddbf4
mark2_foreground #0b0c16
mark2_background #82fb9c
mark3_foreground #0b0c16
mark3_background #c4d2ed

# The 16 terminal colors

# black
color0 #1f253a
color8 #2d3450

# red
color1 #50f872
color9 #50f872

# green
color2  #4fe88f
color10 #4fe88f

# yellow
color3  #50f7d4
color11 #50f7d4

# blue
color4  #829dd4
color12 #829dd4

# magenta
color5  #86a7df
color13 #86a7df

# cyan
color6  #7cf8f7
color14 #7cf8f7

# white
color7  #b5c5db
color15 #6a6e95
