#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
if [[ -n $HOME/.oh-my-zsh/custom ]]; then
  rm -rf $HOME/.oh-my-zsh/custom
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

$HOME/.tmux/plugins/tpm/bin/install_plugins
$HOME/.tmux/plugins/tpm/bin/update_plugins all
