$rosewater = rgb(c0caf5)
$rosewaterAlpha = c0caf5

$flamingo = rgb(ff7a93)
$flamingoAlpha = ff7a93

$pink = rgb(bb9af7)
$pinkAlpha = bb9af7

$mauve = rgb(ad8ee6)
$mauveAlpha = ad8ee6

$red = rgb(f7768e)
$redAlpha = f7768e

$maroon = rgb(eb927b)
$maroonAlpha = eb927b

$peach = rgb(e0af68)
$peachAlpha = e0af68

$yellow = rgb(e0af68)
$yellowAlpha = e0af68

$green = rgb(9ece6a)
$greenAlpha = 9ece6a

$teal = rgb(449dab)
$tealAlpha = 449dab

$sky = rgb(0db9d7)
$skyAlpha = 0db9d7

$sapphire = rgb(7da6ff)
$sapphireAlpha = 7da6ff

$blue = rgb(7aa2f7)
$blueAlpha = 7aa2f7

$lavender = rgb(bb9af7)
$lavenderAlpha = bb9af7

$text = rgb(c0caf5)
$textAlpha = c0caf5

$subtext1 = rgb(b4bee6)
$subtext1Alpha = b4bee6

$subtext0 = rgb(a9b1d6)
$subtext0Alpha = a9b1d6

$overlay2 = rgb(b4bee6)
$overlay2Alpha = b4bee6

$overlay1 = rgb(a9b1d6)
$overlay1Alpha = a9b1d6

$overlay0 = rgb(565f89)
$overlay0Alpha = 565f89

$surface2 = rgb(414868)
$surface2Alpha = 414868

$surface1 = rgb(292e42)
$surface1Alpha = 292e42

$surface0 = rgb(24283b)
$surface0Alpha = 24283b

$base = rgb(1a1b26)
$baseAlpha = 1a1b26

$mantle = rgb(13141c)
$mantleAlpha = 13141c

$crust = rgb(0e0e14)
$crustAlpha = 0e0e14
