# The basic colors
foreground              #c0caf5
background              #1a1b26
selection_foreground    #1a1b26
selection_background    #c0caf5

# Cursor colors
cursor                  #c0caf5
cursor_text_color       #1a1b26

# URL underline color when hovering with mouse
url_color               #c0caf5

# Kitty window border colors
active_border_color     #bb9af7
inactive_border_color   #565f89
bell_border_color       #e0af68

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0e0e14
active_tab_background   #ad8ee6
inactive_tab_foreground #c0caf5
inactive_tab_background #13141c
tab_bar_background      #0e0e14

# Colors for marks (marked text in the terminal)
mark1_foreground #1a1b26
mark1_background #bb9af7
mark2_foreground #1a1b26
mark2_background #ad8ee6
mark3_foreground #1a1b26
mark3_background #7da6ff

# The 16 terminal colors

# black
color0 #292e42
color8 #414868

# red
color1 #f7768e
color9 #f7768e

# green
color2  #9ece6a
color10 #9ece6a

# yellow
color3  #e0af68
color11 #e0af68

# blue
color4  #7aa2f7
color12 #7aa2f7

# magenta
color5  #bb9af7
color13 #bb9af7

# cyan
color6  #449dab
color14 #449dab

# white
color7  #b4bee6
color15 #a9b1d6
