hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("swaync")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nextcloud --background")
    hl.exec_cmd("localsend --hidden")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste -t text -w xclip -selection clipboard")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


