-- Generated by nwg-displays on 2026-09-24 at 12:39:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
